### PR TITLE
Only set cmake generator if explicitly specified

### PR DESCRIPTION
**Pull request by jeikabu**
- Depend on default cmake behavior (see #23)

### CODE REVIEW

**Comment by neachdainn** [comment]
Looks good to me. A few questions though:

1. Does the CI test against Windows at all? For some reason I thought it did but I'm not finding any evidence of that.
2. If the CI doesn't check it, you've been checking it, right?
3. Do you want me to push an `nng-sys v1.1.1-rc.3` when this is merged?

**Comment by jeikabu** [comment]
1. It was: [appveyor](https://ci.appveyor.com/project/jake-ruyi/nng-rust/branch/master).  But it looks like it hasn't been getting triggered for some reason. Maybe I should just use Travis for everything...
1.  Most things I do on both Windows and macOS.
1.  Some people on Windows might get switched to VS2019

**Comment by neachdainn** [comment]
1/2. If you have tested it, it works for you, and you're comfortable pushing it, then that's good enough for me. I definitely consider Windows a Tier 2 platform for most of my stuff simply based on my inability to thoroughly test things on it, so I will defer to your judgment.
3. I'm not sure if that is a "yes" or a "no". It seems to me like that is a potential breaking issue that we are going to have to face at some point, might as well make it now?

**Comment by jeikabu** [comment]
Windows builds should be working again.
Let's say "no".  It could only cause problems.

**Comment by neachdainn** [comment]
> Let's say "no". It could only cause problems.

So have it go out with `v1.2.0-rc.1`? Should we merge this into `feature/nng_1.2` instead of master, then?

**Comment by jeikabu** [comment]
Makes sense.  Will do that.

**Pull request closed without merging**
