### PR TITLE
nng@v1.4.0

### PR DESCRIPTION
**Pull request by jeikabu**

### CODE REVIEW

**Comment by neachdainn** [comment]
I will look this over soon.

**Comment by neachdainn** [comment]
Sorry it took me so long to get this done.

The only concern I have is that `size_t` is now a `u64` instead of a `usize`, which will probably break things that aren't 64-bit. Previous versions did not have this issue but I don't see any changes to the bindgen settings, so I'm not sure how to address this.

**Review by neachdainn — CHANGES_REQUESTED** [review]
Sorry it took me so long to get this done.

The only concern I have is that `size_t` is now a `u64` (technically a `long long`) instead of a `usize`, which will probably break things that aren't 64-bit. Previous versions did not have this issue but I don't see any changes to the bindgen

**Comment by janjaapbos** [comment]
@neachdainn is your comment related to the following issue in bindgen, requiring the switch --size_t-is-usize?
See https://github.com/rust-lang/rust-bindgen/issues/1671

**Comment by janjaapbos** [comment]
It works for me when I add .size_t_is_usize(true) to build.rs. Also I need to hide the new NNG_AF_ABSTRACT socket.
With the diff below, I get a crate that can be used by nng-rs.


diff --git a/build.rs b/build.rs
index 917d177..22d5d86 100644
--- a/build.rs
+++ b/build.rs
@@ -116,6 +116,7 @@ fn build_bindgen() {
         .constified_enum("nng_pipe_ev")
         .use_core()
         .parse_callbacks(Box::new(BindgenCallbacks::default()))
+        .size_t_is_usize(true)
         // Layout tests are non-portable; 64-bit tests are "wrong" size on 32-bit and always fail.
         // Don't output tests if we're regenerating `src/bindings.rs` (shared by all platforms when bindgen not used)
         .layout_tests(!cfg!(feature = "source-update-bindings"));
@@ -169,6 +170,9 @@ impl bindgen::callbacks::ParseCallbacks for BindgenCallbacks {
         // We want to exclude it so it doesn't need to be included for `match` to be exhaustive.
         if original_variant_name == "NNG_PIPE_EV_NUM" {
             Some(bindgen::callbacks::EnumVariantCustomBehavior::Hide)
+        // NNG abstract sockets are only supported on Linux and non-portable
+        } else if original_variant_name == "NNG_AF_ABSTRACT" {
+            Some(bindgen::callbacks::EnumVariantCustomBehavior::Hide)
         } else {
             None
         }

**Comment by jeikabu** [comment]
Closing this in favor of #32

**Pull request closed without merging**
