### PR TITLE
Changes for nng v1.4.0

### PR DESCRIPTION
**Pull request by janjaapbos**
This works with the current nng-rs.

### CODE REVIEW

**Comment by neachdainn** [comment]
Is this pull request the changes from #31 with your comments applied?

**Comment by janjaapbos** [comment]
Yes, my changes are based on the 1.4.0 branch by @jeikabu

**Comment by jeikabu** [comment]
Looks ok to me

**Comment by jeikabu** [comment]
@neachdainn were you going to give it another look, or can I merge?

**Pull request merged**
